import type { Contratacao } from '@/types/pncp';
import type { LicitacaoRow } from '@/types/db';

// Converte uma linha do Supabase → formato da API PNCP (usado no frontend)
export function rowToContratacao(row: LicitacaoRow): Contratacao {
  return {
    srp:                               row.srp,
    anoCompra:                         row.ano_compra ?? 0,
    sequencialCompra:                  row.sequencial_compra ?? 0,
    numeroControlePNCP:                row.numero_controle_pncp,
    numeroCompra:                      row.numero_compra ?? '',
    processo:                          row.processo ?? '',
    objetoCompra:                      row.objeto_compra,
    informacaoComplementar:            row.informacao_complementar,
    dataInclusao:                      row.data_inclusao ?? '',
    dataPublicacaoPncp:                row.data_publicacao_pncp ?? '',
    dataAtualizacao:                   row.data_atualizacao ?? '',
    dataAberturaProposta:              row.data_abertura_proposta ?? '',
    dataEncerramentoProposta:          row.data_encerramento_proposta ?? '',
    modalidadeId:                      row.modalidade_id ?? 0,
    modalidadeNome:                    row.modalidade_nome ?? '',
    situacaoCompraId:                  row.situacao_compra_id ?? 0,
    situacaoCompraNome:                row.situacao_compra_nome ?? '',
    modoDisputaId:                     row.modo_disputa_id ?? 0,
    modoDisputaNome:                   row.modo_disputa_nome ?? '',
    tipoInstrumentoConvocatorioCodigo: row.tipo_instrumento_codigo ?? 0,
    tipoInstrumentoConvocatorioNome:   row.tipo_instrumento_nome ?? '',
    valorTotalEstimado:                row.valor_total_estimado,
    valorTotalHomologado:              row.valor_total_homologado,
    usuarioNome:                       row.usuario_nome ?? '',
    linkSistemaOrigem:                 row.link_sistema_origem,
    linkProcessoEletronico:            row.link_processo_eletronico,
    justificativaPresencial:           row.justificativa_presencial,
    emendaParlamentar:                 row.emenda_parlamentar,
    fontesOrcamentarias:               [],
    orgaoEntidade: {
      cnpj:        row.orgao_cnpj ?? '',
      razaoSocial: row.orgao_razao_social ?? '',
      poderId:     row.orgao_poder_id ?? '',
      esferaId:    row.orgao_esfera_id ?? '',
    },
    unidadeOrgao: {
      ufNome:        row.uf_nome ?? '',
      codigoUnidade: row.codigo_unidade ?? '',
      nomeUnidade:   row.nome_unidade ?? '',
      ufSigla:       row.uf_sigla ?? '',
      municipioNome: row.municipio_nome ?? '',
      codigoIbge:    row.codigo_ibge ?? '',
    },
    amparoLegal: {
      descricao: row.amparo_legal_descricao ?? '',
      nome:      row.amparo_legal_nome ?? '',
      codigo:    row.amparo_legal_codigo ?? 0,
    },
  };
}

// Converte um objeto Contratacao (API PNCP) → linha para upsert no Supabase
export function contratacaoToRow(c: Contratacao): Omit<LicitacaoRow, 'sincronizado_em'> {
  return {
    numero_controle_pncp:       c.numeroControlePNCP,
    srp:                        c.srp,
    ano_compra:                 c.anoCompra,
    sequencial_compra:          c.sequencialCompra,
    numero_compra:              c.numeroCompra || null,
    processo:                   c.processo || null,
    objeto_compra:              c.objetoCompra,
    informacao_complementar:    c.informacaoComplementar,
    data_inclusao:              c.dataInclusao || null,
    data_publicacao_pncp:       c.dataPublicacaoPncp || null,
    data_atualizacao:           c.dataAtualizacao || null,
    data_abertura_proposta:     c.dataAberturaProposta || null,
    data_encerramento_proposta: c.dataEncerramentoProposta || null,
    modalidade_id:              c.modalidadeId,
    modalidade_nome:            c.modalidadeNome,
    situacao_compra_id:         c.situacaoCompraId,
    situacao_compra_nome:       c.situacaoCompraNome,
    modo_disputa_id:            c.modoDisputaId,
    modo_disputa_nome:          c.modoDisputaNome,
    tipo_instrumento_codigo:    c.tipoInstrumentoConvocatorioCodigo,
    tipo_instrumento_nome:      c.tipoInstrumentoConvocatorioNome,
    valor_total_estimado:       c.valorTotalEstimado,
    valor_total_homologado:     c.valorTotalHomologado,
    usuario_nome:               c.usuarioNome || null,
    link_sistema_origem:        c.linkSistemaOrigem,
    link_processo_eletronico:   c.linkProcessoEletronico,
    justificativa_presencial:   c.justificativaPresencial,
    emenda_parlamentar:         c.emendaParlamentar,
    orgao_cnpj:                 c.orgaoEntidade.cnpj || null,
    orgao_razao_social:         c.orgaoEntidade.razaoSocial || null,
    orgao_poder_id:             c.orgaoEntidade.poderId || null,
    orgao_esfera_id:            c.orgaoEntidade.esferaId || null,
    uf_sigla:                   c.unidadeOrgao.ufSigla || null,
    uf_nome:                    c.unidadeOrgao.ufNome || null,
    municipio_nome:             c.unidadeOrgao.municipioNome || null,
    codigo_ibge:                c.unidadeOrgao.codigoIbge || null,
    codigo_unidade:             c.unidadeOrgao.codigoUnidade || null,
    nome_unidade:               c.unidadeOrgao.nomeUnidade || null,
    amparo_legal_codigo:        c.amparoLegal.codigo,
    amparo_legal_nome:          c.amparoLegal.nome || null,
    amparo_legal_descricao:     c.amparoLegal.descricao || null,
  };
}
